name: Build Container Images

on:
  workflow_dispatch:
    inputs:
      build_base:
        description: 'Build base image'
        required: false
        default: true
        type: boolean
      build_main:
        description: 'Build main image'
        required: false
        default: true
        type: boolean
      branch:
        description: 'Branch to build from'
        required: false
        default: 'main'
        type: string

env:
  REGISTRY: ghcr.io
  BASE_IMAGE_NAME: ${{ github.repository }}-base
  MAIN_IMAGE_NAME: ${{ github.repository }}-run

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push base image
        if: ${{ inputs.build_base == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: ./docker/base
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}:${{ inputs.branch }}
            ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
          build-args: |
            CACHE_DATE=${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push main image
        if: ${{ inputs.build_main == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: ./docker/run
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.MAIN_IMAGE_NAME }}:${{ inputs.branch }}
            ${{ env.REGISTRY }}/${{ env.MAIN_IMAGE_NAME }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
          build-args: |
            BRANCH=${{ inputs.branch }}
            CACHE_DATE=${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max